### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by timmo001** [timmo001/iseries-api#1]
# Description

This is a tracking issue for initial development. Do not close until checklist is complete

## Todo List

- [x] Add library `node-jt400`
- [x] Add SQL endpoint using first command as method
- [x] Add batch insert support
- [x] Add IFS endpoint
- [x] Add PGM endpoint
- [x] Add message endpoint
- [x] Add Websocket

**Comment by timmo001** [comment]
Done! Releasing soon
